[package]
name = "penenv"
version = "1.0.0"
edition = "2021"

[dependencies]
gtk4 = "0.9"
libadwaita = "0.7"
chrono = "0.4"
vte4 = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
sysinfo = "0.32"
